INSERT INTO `setor` (`id`, `nome`) VALUES
	(1, 'Direção'),
	(2, 'Coordenação acadêmica'),
	(3, 'Coordenação de cursos'),
	(4, 'Divisão de pesquisa e extensão'),
	(5, 'Coordenação administrativa'),
	(6, 'Protocolo'),
	(7, 'Gerência de biblioteca'),
	(8, 'Serviço de referência de biblioteca'),
	(9, 'Gerência de recursos humanos'),
	(10, 'Divisão de assuntos estudantis'),
	(11, 'Acessibilidade'),
	(12, 'Gerência de orçamento e finanças'),
	(13, 'Gerência de licitação'),
	(14, 'Gerência de patrimônio, materiais e manutenção'),
	(15, 'Setor de arquitetura'),
	(16, 'Gerência de TI'),
	(17, 'Gestão de contratos'),
	(18, 'Coordenação de biologia'),
	(19, 'Coordenação de matemática e física'),
	(20, 'Coordenaçãoo de engenharia de produção'),
	(21, 'Coordenação de engenharia de software'),
	(22, 'Coordenação de engenharia sanitária e ambiental'),
	(23, 'Coordenação farmácia'),
	(24, 'Coordenação pedagogia'),
	(25, 'Coordenação química industrial'),
	(26, 'Coordenação sistema de informação'),
	(27, 'Coordenação química e biologia');
