INSERT INTO `setor` (`id`, `nome`) VALUES
	(1, 'Biblioteca'),
	(2, 'Coordenação acadêmica'),
	(3, 'Gerência de TI'),
	(4, 'Direção'),
	(5, 'Coordenação administrativa'),
	(6, 'Transporte'),
	(7, 'Departamento de Recursos Humanos'),
	(8, 'Secretaria Acadêmica'),
	(9, 'Departamento de Engenharia'),
	(10, 'Departamento de Ciência da Computação'),
	(11, 'Departamento de Arquitetura'),
	(12, 'Departamento de Design'),
	(13, 'Departamento de Economia'),
	(14, 'Departamento de Administração'),
	(15, 'Departamento de Direito'),
	(16, 'Coordenação de Pós-Graduação'),
	(17, 'Departamento de Química'),
	(18, 'Departamento de Biologia'),
	(19, 'Departamento de Matemática'),
	(20, 'Departamento de Física'),
	(21, 'Departamento de História'),
	(22, 'Departamento de Geografia'),
	(23, 'Departamento de Letras'),
	(24, 'Coordenação de Extensão');